global:
  scrape_interval: 15s

rule_files:
  - rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets: ["localhost:9093"]
    
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'node-exporter'
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: 'simple_server'
    static_configs:
      - targets: ["localhost:8090"]

  - job_name: 'app-py'
    static_configs:
      - targets: ["localhost:3001"]

 